name: Comment 
on: pull_request
jobs:
  comment: 
    runs-on: ubuntu-24.04-arm64
    permissions: 
      pull-requests: write 
      contents: read 
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REFF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}